spring:
  application:
    name: xmen-dna-analyzer
  data:
    mongodb:
      database: dna-analyzer
      port: 27017
      host: 18.221.36.90

logging:
  pattern:
    level: debug

server:
  servlet:
    context-path: /dna.analyzer
  compression:
    enabled: true
  tomcat:
    threads:
      max: 100

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
